### ISSUE TITLE
Missing installation / compilation instructions

### ISSUE THREAD

**Issue by RGD2** [tenox7/regln#3]
How does one deploy this? Which compiler should be used? 

Is there a signed,  pre-built executable anywhere?

I was linked to this project from <https://pupuweb.com/solved-fix-error-opening-registry-key/>, and that pages just says to copy the .c file straight to C:\Windows\System32\ ... 

This made me raise and eyebrow, I tried it without luck anyway.

Just consider this ticket to be a fault with README.md - it's generally nice if there's at least a short mention of the tools and procedure needed to get a project up and running.

**Comment by RGD2** [comment]
Aha, there are releases here: <https://github.com/tenox7/regln/releases>

**Comment by RGD2** [comment]
Maybe, at most, a line near the top that says something like:

# Releases

See releases to the right, here -> 

Well, maybe it's just me.

**Comment by tenox7** [comment]
Yeah a link could be added I guess :)
